### ISSUE TITLE
SSH Key support

### ISSUE THREAD

**Issue by wheelerlaw** [ad-m/github-push-action#110]
Currently there is no support for using SSH keys for pushing to a repo. Why might one want to use this? For [Deploy Keys](https://docs.github.com/en/developers/overview/managing-deploy-keys), which are SSH keys for GitHub but are tied to a repo rather than a user. Using Deploy Keys is an alternative solution to using admin bot account for commit back to a repo on a branch that has branch protections.

**Comment by ZPascal** [comment]
This sounds like a useful function to me. I will check how to implement such a functionality inside the action. I think, I can deliver the first results in next two weeks.

**Comment by ad-m** [comment]
@wheelerlaw what about use https://github.com/marketplace/actions/install-ssh-key and call git directly (see #104)?

@ZPascal I added you as a contributor. Feel free to contribute that feature if you want. I am still looking for any sense in investing my time in this acction, except maintaining backward compatibility of ecosystem (I use it in a few places because I haven't updated).

**Comment by ZPascal** [comment]
Hi @ad-m @wheelerlaw,

I've implemented [here](https://github.com/ad-m/github-push-action/pull/115) a first version of the SSH Key support functionality.
