### ISSUE TITLE
fatal: --local can only be used inside a git repository

### ISSUE THREAD

**Issue by DevJamesC** [ad-m/github-push-action#123]
Hi, I'm trying to push the artifact (a zip file) from a private repository to a public one.
I use actions/checkout@v3 to clone the repository.
I then cd into the repo, move my file into the root, add and commit changes successfully.
Then the github-push-action in my next step throws this error

"Push to branch main
fatal: --local can only be used inside a git repository
Error: Invalid exit code: 128"

I tried setting the ad-m/github-push-action@master "directory" input to "." to a var of the absolute path to the repo directory, and to default. I get the error each time. I'm pretty sure I'm in a git repo! Anyone have any idea what is going on?

**Comment by ZPascal** [comment]
@DevJamesC I've got the same problem with another [action](https://github.com/tj-actions/verify-changed-files). I've already checked the checkout action and seams there is no change since days. The commonality of the two failed actions is that both execute `git --local` commands. I will give you feedback as soon as I find a solution.

**Comment by ZPascal** [comment]
I've temporarily solved the issue by adding a separate step after the checkout to set the safe directory again.
```YAML
      - name: Specify the Git global safe directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
```

**Comment by DevJamesC** [comment]
Thanks! I'll give it a try!
