### ISSUE TITLE
Use JavaScript syntax

### ISSUE THREAD

**Issue by paced** [ad-m/github-push-action#26]
The JavaScript syntax is significantly faster than using a `Dockerfile`. For a tool like this, it could be easy to make the conversion.

I did this in [my fork](https://github.com/teaminkling/skip-commit) from [veggiemonk/skip-commit](https://github.com/veggiemonk/skip-commit) and I see gains of ~27 seconds:

![image](https://user-images.githubusercontent.com/15013453/68675022-1ea68f00-05ab-11ea-864e-b9ee20a573ce.png)

The top build is after I switched to JS, the bottom is with a Dockerfile.

This makes sense: the old Docker image build step took ~25 seconds before I switched.

**Comment by tenhobi** [comment]
This is true for the current state of Github Actions because they lack the support of caching.

After the caching will be available, there should be no difference in time needed +, in general, it is safer to use Docker, because it works in a separate container, etc.

For now, of course, we should consider using some version w/o Docker, because we do not really use the functionality it provides, I suppose? Cc @ad-m

**Comment by paced** [comment]
Agreed. Personally, I wish they would allow us to write everything in Python but for now, Node is the only thing that allows me to keep things fairly fast.

**Comment by ad-m** [comment]
Fixed in #29 .
