### ISSUE TITLE
Race condition on parallel builds

### ISSUE THREAD

**Issue by paced** [ad-m/github-push-action#27]
This is especially the case if you try to push a tag and a commit at the same time. I believe a possible resolution would simply be to pull before a push. Perhaps an extra configuration item for those fearing this could be useful?

**Comment by ad-m** [comment]
Our library only performs atomic push operations. However, users often combine our actions with "checkout" or a similar solution, because the action does not have its own application. So race-condition concerns how users use our action along with other actions. I wonder (I don't know) if race-condition prevention is the responsibility of this action.

**Comment by paced** [comment]
That's a good point. A simple workflow step to perform a `git pull --rebase` would _probably_ solve this and that would be a lot simpler than modifying the Action to do this with new configuration options.

Still, maybe documentation should be updated to reflect this? I'm not sure how common this race condition will be with users, though.

Thanks for the reply!

**Comment by ad-m** [comment]
How conflicts in race-conditions are resolved depends on the user's use case. Currently, the action does not overwrite data if force-push is not used (disabled by default).

I use the above actions as part of a tool that:
- download fresh data from the government,
- sends a newsletter with changed items,
- save changes to the repository.
In my case, I accept that some changes will not be saved in case of conflict in race-condition, because at most some information will be repeated items in newsletter. Lost some changes impact very low losses, as one action execution contains 3-8 items, and the action is performed 3 times a day each business day.It is more important for me that the data structure is not damaged by automatic conflict resolution, because then I have to correct the process manually. For me the most important is the process must be automatic to keep maintenance cost low.

**Comment by paced** [comment]
Yeah, that makes sense. It's definitely up to the use case. For me, the chance of conflict is extremely minimal and resolution in the pipeline would fail the build anyway, so adding the changes to the `main.yaml` workflow will suffice for me.

A resolution to pull is much more difficult than I initially thought. A `git pull` needs to be written as such:

```
git pull origin ${{github.ref}} --rebase
```

This will fail if a tag causes a commit and push and happens before another push that triggers a workflow. Unfortunately, it means that it is not possible for me, currently, to "gracefully" resolve this race condition.

I will retract the PR as it's not accurate. Thanks for the responses!
